version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - webnet

networks:
  webnet: